### ISSUE TITLE
Bug with MyJailbreak

### ISSUE THREAD

**Issue by Javierko** [Sples1/sm-hosties-fixed#1]
Hello, 
i am testing myjailbreak and new hosties, after shanapu´s remake of events, he addded "ToggleWeaponFire" and after that, i cant shoot or use gun after starting any mod, on end of mod or new round, still i cant use guns or knife. Maybe you can fix it in new version. Thanks.

https://github.com/shanapu/MyJailbreak/commit/71fc3270e3871de782ab926e5cca2ec4d8153dfe#diff-f02dd81c20ed70918a94144d4e4076cfR229

**Comment by Sples1** [comment]
Hey! I'll take a look on it!

**Comment by shanapu** [comment]
hi, I'm the author of MyJailbreak. 
As I see in [the reported error](https://hastebin.com/erebakilaq.cpp) from Javierko, the issue result from this line: https://github.com/Sples1/sm-hosties-fixed/blob/master/addons/sourcemod/scripting/sm_hosties_e.sp#L63 (that I just saw fixed in beta)
This has nothing to do with the said commit.

Good work, even if I would have used the existing fixes from original beta branch and forks as a basis to be able to continue writing in new syntax. Don't forget to make some pull requests against the main repo if possible. ;)    **keep up good work!**

PS: You should change your version numbers in master/beta, to indentify the different versions. I also recommend to not remove existing natives, forwards & cvars to keep compatibility with existing plugins.

**Comment by Sples1** [comment]
Thank you very much. I want to keep it Up2Date as I can. :/ I want to upgrade to use new Syntax but it will be dew days for sure.

I was thinking about to stop the project because of the feedbacks. You and Bara told to continue... So I will.

Thanks for the tips, I appreciate that very much.
